
# Added by shell-dev-env.
# =Begin= 
source $HOME/.shell-dev-env/env/bash/statusbar.bashrc
source $HOME/.shell-dev-env/env/bash/aliases.bashrc
source $HOME/.shell-dev-env/env/bash/variables.bashrc
# =End=

