
# Added by shell-dev-env.
# =Begin=
# source $ENV_ROOT/env/zsh/statusbar.zsh
#source $ENV_ROOT/env/zsh/antigen.zsh
source $ENV_ROOT/env/zsh/zgen.zsh
source $ENV_ROOT/env/zsh/settings.zsh
source $ENV_ROOT/env/zsh/aliases.zsh
# =End=
